<!DOCTYPE html>
<html>
    <head>
        <title>Mini-projet Authentification</title>
    </head>
    <body>
        <?php 
            if ($route === "home" || $route === null) {
                require "home.phtml";
            } else if ($route === "inscription") {
                 require "register.phtml";
            } else if ($route === "connexion") {
                require "login.phtml";
            }
        ?>
    </body>
</html>