<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
   <form action="logic/register.php" method="post">
    <fieldset>
        <label for="firstname">Prénom</label>
        <input type="text" name="first_name" id="firstname"/>
    </fieldset>
    <fieldset>
        <label for="lastname">Nom</label>
        <input type="text" name="last_name" id="lastname"/>
    </fieldset>
    <fieldset>
        <label for="email">Email</label>
        <input type="email" name="email" id="email"/>
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe</label>
        <input type="password" name="password" id="password"/>
    </fieldset>
    <fieldset>
        <input type="submit" value="Inscription"/>
    </fieldset>
</form>
</body>
</html>
</html>